In [14]:
%matplotlib inline
import torch
import torchvision
from torch.utils import data
from torchvision import transforms
from IPython import display


In [15]:
import IPython
print(IPython.__version__) # 作为jupyter的依赖自动安装好了

9.15.0


In [16]:
def get_dataloader_workers():
    """使用4个进程读取数据"""
    return 0

In [17]:
# 整合所有的组件, 获取FashionMNIST数据集，返回训练集和验证集的数据迭代器

def load_data_fashion_mnist(batch_size, resize=None):
    """下载FashionMNIST的数据集，然后将其加载到内存中"""
    trans = [transforms.ToTensor()]
    if resize:
        trans.insert(0, transforms.Resize(resize))
    trans = transforms.Compose(trans)
    mnist_train = torchvision.datasets.FashionMNIST(
        root="../data", train=True, transform=trans, download=True
    ) 
    mnist_test = torchvision.datasets.FashionMNIST(
        root="../data", train=False, transform=trans, download=True
    ) 

    return (data.DataLoader(mnist_train, batch_size, shuffle=True, 
                num_workers=get_dataloader_workers()),
            data.DataLoader(mnist_train, batch_size, shuffle=True,
                num_workers=get_dataloader_workers()))

In [18]:
batch_size = 32
train_iter, test_iter = load_data_fashion_mnist(batch_size, resize=None)

In [19]:
num_inputs = 784
num_outputs = 10

In [20]:
display.display("hello")

'hello'

In [21]:
w = torch.normal(0, 0.01, size=(num_inputs, num_outputs), requires_grad=True)
b = torch.zeros(num_outputs, requires_grad=True)
w, w.shape, b, b.shape

(tensor([[ 0.0128,  0.0107,  0.0005,  ...,  0.0017, -0.0108, -0.0154],
         [ 0.0138,  0.0075, -0.0021,  ...,  0.0029, -0.0063, -0.0114],
         [ 0.0085, -0.0022, -0.0073,  ..., -0.0062,  0.0075,  0.0005],
         ...,
         [-0.0231, -0.0017, -0.0074,  ..., -0.0146, -0.0121, -0.0070],
         [-0.0120, -0.0004, -0.0075,  ...,  0.0142, -0.0022, -0.0087],
         [ 0.0095,  0.0033,  0.0240,  ...,  0.0030, -0.0095,  0.0014]],
        requires_grad=True),
 torch.Size([784, 10]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True),
 torch.Size([10]))

In [24]:
# 定义softmax操作

X = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
X.sum(0, keepdim=True), X.sum(1, keepdim=True)

(tensor([[5., 7., 9.]]),
 tensor([[ 6.],
         [15.]]))

In [25]:
def softmax(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(1, keepdim=True)
    return X_exp / partition # 这里使用了广播机制

In [29]:
X = torch.normal(0, 1, (2, 5))
print(X)
X_prob = softmax(X)
print(X_prob, X_prob.sum(1), sep='\n')

tensor([[-2.0730, -1.2911,  0.4143,  0.1832,  0.3005],
        [ 0.7577, -1.2528, -0.1665,  0.4107,  0.2780]])
tensor([[0.0282, 0.0616, 0.3389, 0.2690, 0.3024],
        [0.3501, 0.0469, 0.1389, 0.2474, 0.2167]])
tensor([1., 1.])
