In [42]:
import torch 

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [43]:
x.requires_grad_(True)
x.grad

In [44]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [45]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [46]:
x.grad == 4 * x

tensor([True, True, True, True])

In [47]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [48]:
x.grad.zero_()
y = x * x
print("y: ", y)
y.sum().backward()
x.grad

y:  tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)


tensor([0., 2., 4., 6.])

In [49]:
# 分离计算

x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad, u, u == x.grad

(tensor([0., 1., 4., 9.]),
 tensor([0., 1., 4., 9.]),
 tensor([True, True, True, True]))

In [50]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [51]:
# Python 控制流的梯度计算

def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [52]:
a = torch.randn(size=(), requires_grad=True)
print(a)
d = f(a)
d.backward()

tensor(0.8571, requires_grad=True)


In [54]:
print(a.grad) 
a.grad == d / a

tensor(2048.)


tensor(True)