In [75]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)
x, y, x + y, x - y, x * y, x / y, x ** y

(tensor(3.),
 tensor(2.),
 tensor(5.),
 tensor(1.),
 tensor(6.),
 tensor(1.5000),
 tensor(9.))

In [76]:
# Vector
x = torch.arange(4)
x, x.shape, x.size()

(tensor([0, 1, 2, 3]), torch.Size([4]), torch.Size([4]))

In [77]:
x[3]

tensor(3)

In [78]:
len(x) # 向量的长度

4

In [79]:
x.shape

torch.Size([4])

In [80]:
x = x.reshape(2, -1)
x, x.shape

(tensor([[0, 1],
         [2, 3]]),
 torch.Size([2, 2]))

In [81]:
x = x.reshape(4)
x

tensor([0, 1, 2, 3])

In [82]:
# Matrix
A = torch.arange(20).reshape(5, -1)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [83]:
# Transpose of Matrix
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [84]:
# 对称矩阵
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [85]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [86]:
A[1, 1]

tensor(5)

In [87]:
# Tensor
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [88]:
X[1, 1, 1]

tensor(17)

In [89]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()
A, A + B


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [90]:
# 哈达玛积
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [91]:
# 张量加/乘一个标量
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [92]:
# 降维
x = torch.arange(4, dtype=torch.float32)
x, x.sum() # 向量的所有元素的和

(tensor([0., 1., 2., 3.]), tensor(6.))

In [93]:
print(A) 
A.shape, A.sum()

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


(torch.Size([5, 4]), tensor(190.))

In [94]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [95]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [96]:
A.sum(axis=[0, 1]), A.sum()

(tensor(190.), tensor(190.))

In [97]:
# 平均值
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [98]:
A.mean(axis=0) # 指定轴也可以降低维度，等价于
A.sum(axis=0) / A.shape[0], A.mean(axis=0) # A.shape[0], 等价于第零轴长度

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [99]:
# 非降维求和，行第一维长度变1了
sum_A = A.sum(axis=0, keepdim=True)
sum_A

tensor([[40., 45., 50., 55.]])

In [100]:
print(A, sum_A, sep='\n')
A / sum_A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[40., 45., 50., 55.]])


tensor([[0.0000, 0.0222, 0.0400, 0.0545],
        [0.1000, 0.1111, 0.1200, 0.1273],
        [0.2000, 0.2000, 0.2000, 0.2000],
        [0.3000, 0.2889, 0.2800, 0.2727],
        [0.4000, 0.3778, 0.3600, 0.3455]])

In [101]:
sum_A = A.sum(axis=1, keepdim=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [102]:
print(A, sum_A, sep='\n')
A / sum_A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])


tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [104]:
print(A.cumsum(axis=0))
print(A.cumsum(axis=1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])
tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]])


In [ ]:
# 点积 dot product
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [108]:
torch.sum(x * y)

tensor(6.)

In [109]:
# 矩阵向量乘积
A.shape, x.shape, torch.mv(A, x) # matrix dot vector

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [110]:
# 矩阵矩阵乘法
B = torch.ones(4, 3)
print(A)
print(B)
torch.mm(A, B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [ ]:
# 范数 norm
u = torch.tensor([3., 4.])
torch.norm(u) # L2 范数

tensor(5.)

In [116]:
u = torch.randn(4, dtype=torch.float32)
u, torch.abs(u).sum()

(tensor([-0.9955,  0.5708,  1.6007,  0.7574]), tensor(3.9244))

In [ ]:
# 矩阵的Frobenius范数
print(A)
torch.norm(A)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


tensor(49.6991)

In [121]:
# A.t.t = A
A = torch.randn(12).reshape(3, 4)
A, A == A.T.T

(tensor([[-0.5177,  0.4118, -0.9381,  0.2737],
         [ 0.3051, -0.1588,  1.6834, -0.5760],
         [ 2.1910, -1.1707, -0.4015, -0.2748]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [122]:
# 转置的和等于和的转置
B = torch.randn(12).reshape(3, 4)
A.T + B.T == (A + B).T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])

In [125]:
print(X)
len(X)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


2

In [128]:
A[:] = torch.arange(12).reshape(3, 4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [130]:
print(A)
print(A.sum(axis=1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([ 6., 22., 38.])


In [135]:
print(X)
print(X.sum(axis=0))
print(X.sum(axis=1))
print(X.sum(axis=2))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
tensor([[ 6, 22, 38],
        [54, 70, 86]])
